input CreateUser {
  email: EmailAddress!
  name: String!
  description: String
  password: String!
  github: String
  linkedin: String
}
input UpdateUser {
  email: EmailAddress!
  name: String
  password: String
  description: String
  old_password: String
  github: String
  linkedin: String
  avatar_url: URL
}
input DeleteUser {
  email: EmailAddress!
}
input LoginData {
  email: EmailAddress!
  password: String!
}
input ResetPassword {
  token: UUID!
  password: String!
  password_confirmation: String!
}

type User {
  id: ObjectID
  name: String!
  email: EmailAddress!
  description: String
  avatar_url: URL
  github: String
  linkedin: String
  created_at: Date!
  updated_at: Date!
  level: Int!
  exp_percent: Float!
  access_level: String!
}
type AuthenticateUser {
  token: ID!
  user: User!
}
type UserActivity {
  postsLiked: Int
  postsCreated: Int
  commentsLiked: Int
  commentsCreated: Int
}
type UserSummary {
  all: UserActivity
  lastMonth: UserActivity
  lastWeek: UserActivity
  weekExp: Int
  lastWeekPosts: [Post]
}
type Query {
  getUser(id: ObjectID!): User
  login(data: LoginData): AuthenticateUser
  userSummary(id: ObjectID!): UserSummary
}
input EmailInput {
  email: EmailAddress!
}
type Mutation {
  createUser(data: CreateUser): User
  updateUser(data: UpdateUser): User
  deleteUser(data: DeleteUser): Void
  forgotPassword(data: EmailInput): Void
  resetPassword(data: ResetPassword): Void
}
