input CreateCategory {
  name: String!
}
type Category {
  id: ObjectID!
  name: String!
}
type Query {
  listCategories: [Category!]
}
type Mutation {
  createCategory(data: CreateCategory!): Category!
}
