input CreateComment {
  post_id: ObjectID!
  body: String!
}
input UpdateComment {
  id: ObjectID!
  body: String!
}
type Comment {
  id: String!
  author: Author!
  created_at: Date!
  updated_at: Date!
  body: String!
  post_id: ObjectID!
  likes: Int!
}
type Mutation {
  likeComment(comment_id: ObjectID!): Int
  createComment(data: CreateComment!): Comment!
  updateComment(data: UpdateComment!): Comment!
  deleteComment(id: ObjectID!): Void
}
