input TagFilter {
  category_id: ObjectID!
}
input CreateTag {
  name: String!
  category_id: ObjectID!
}
input CreatePostTag {
  tag_id: ObjectID!
}
type Tag {
  id: String!
  name: String!
  category: Category!
}
type Query {
  getTag(id: ObjectID!): Tag
  listTags(filter: TagFilter): [Tag]!
}
type Mutation {
  createTag(data: CreateTag!): Tag!
}
